package utils

var CbsTeamCodeToTeamIDmapping map[string]string = map[string]string{
	"louisianamonroe-warhawks":              "ul-monroe-warhawks",
	"fiu-panthers":                          "florida-international-panthers",
	"connecticut-huskies":                   "uconn-huskies",
	"miami-fla-hurricanes":                  "miami-hurricanes",
	"middle-tenn-blue-raiders":              "middle-tennessee-blue-raiders",
	"saint-francis-u-red-flash":             "saint-francis-red-flash",
	"appalachian-state-mountaineers":        "app-state-mountaineers",
	"bethunecookman-wildcats":               "bethune-cookman-wildcats",
	"central-connecticut-state-blue-devils": "central-connecticut-blue-devils",
	"albany-great-danes":                    "ualbany-great-danes",
	"liu-sharks":                            "long-island-university-sharks",
	"se-missouri-st-redhawks":               "southeast-missouri-state-redhawks",
	"arkansaspine-bluff-golden-lions":       "arkansas-pine-bluff-golden-lions",
	"southeastern-louisiana-lions":          "se-louisiana-lions",
	"hawaii-rainbow-warriors":               "hawai'i-rainbow-warriors",
	"etsu-buccaneers":                       "east-tennessee-state-buccaneers",
	"grambling-state-tigers":                "grambling-tigers",
	"gardnerwebb-runnin-bulldogs":           "gardner-webb-runnin-bulldogs",
	"delaware-fightin-blue-hens":            "delaware-blue-hens",
	"army-west-point-black-knights":         "army-black-knights",
	"nc-at-aggies":                          "north-carolina-at-aggies",
	"mcneese-state-cowboys":                 "mcneese-cowboys",
	"southern-university-jaguars":           "southern-jaguars",
	"citadel-bulldogs":                      "the-citadel-bulldogs",
}

var FoxTeamCodeToTeamIDmapping map[string]string = map[string]string{
	"saint-francis-red-flash":         "st-francis-pa-red-flash",
	"ut-martin-skyhawks":              "tennessee-martin-skyhawks",
	"app-state-mountaineers":          "appalachian-state-mountaineers",
	"central-connecticut-blue-devils": "central-connecticut-state-blue-devils",
	"ualbany-great-danes":             "university-at-albany-great-danes",
	"long-island-university":          "liu-sharks",
	"nicholls-colonels":               "nicholls-state-colonels",
	"se-louisiana-lions":              "southeastern-louisiana-lions",
	"grambling-tigers":                "grambling-state-tigers",
	"ul-monroe-warhawks":              "louisiana-monroe-warhawks",
	"nc-state-wolfpack":               "north-carolina-state-wolfpack",
	"southern-jaguars":                "southern-university-jaguars",
	"massachusetts-minutemen":         "umass-minutemen",
	"miami-hurricanes":                "miami-fl-hurricanes",
}
