package utils

// Map Type of [TeamID]cbsCode
var TeamIDtoCbsTeamCode map[string]string = map[string]string{
	"ul-monroe-warhawks":                "louisianamonroe-warhawks",
	"florida-international-panthers":    "fiu-panthers",
	"uconn-huskies":                     "connecticut-huskies",
	"miami-hurricanes":                  "miami-fla-hurricanes",
	"middle-tennessee-blue-raiders":     "middle-tenn-blue-raiders",
	"saint-francis-red-flash":           "saint-francis-u-red-flash",
	"app-state-mountaineers":            "appalachian-state-mountaineers",
	"bethune-cookman-wildcats":          "bethunecookman-wildcats",
	"central-connecticut-blue-devils":   "central-connecticut-state-blue-devils",
	"ualbany-great-danes":               "albany-great-danes",
	"long-island-university-sharks":     "liu-sharks",
	"southeast-missouri-state-redhawks": "se-missouri-st-redhawks",
	"arkansas-pine-bluff-golden-lions":  "arkansaspine-bluff-golden-lions",
	"se-louisiana-lions":                "southeastern-louisiana-lions",
	"hawai'i-rainbow-warriors":          "hawaii-rainbow-warriors",
	"east-tennessee-state-buccaneers":   "etsu-buccaneers",
	"grambling-tigers":                  "grambling-state-tigers",
	"gardner-webb-runnin-bulldogs":      "gardnerwebb-runnin-bulldogs",
	"delaware-blue-hens":                "delaware-fightin-blue-hens",
	"army-black-knights":                "army-west-point-black-knights",
	"north-carolina-at-aggies":          "nc-at-aggies",
	"mcneese-cowboys":                   "mcneese-state-cowboys",
	"southern-jaguars":                  "southern-university-jaguars",
	"the-citadel-bulldogs":              "citadel-bulldogs",
}

// Map Type of [TeamID]foxCode
var TeamIDtoFoxTeamCode map[string]string = map[string]string{
	"st-francis-pa-red-flash":               "saint-francis-red-flash",
	"tennessee-martin-skyhawks":             "ut-martin-skyhawks",
	"appalachian-state-mountaineers":        "app-state-mountaineers",
	"central-connecticut-state-blue-devils": "central-connecticut-blue-devils",
	"university-at-albany-great-danes":      "ualbany-great-danes",
	"liu-sharks":                            "long-island-university",
	"nicholls-state-colonels":               "nicholls-colonels",
	"southeastern-louisiana-lions":          "se-louisiana-lions",
	"grambling-state-tigers":                "grambling-tigers",
	"louisiana-monroe-warhawks":             "ul-monroe-warhawks",
	"north-carolina-state-wolfpack":         "nc-state-wolfpack",
	"southern-university-jaguars":           "southern-jaguars",
	"umass-minutemen":                       "massachusetts-minutemen",
	"miami-fl-hurricanes":                   "miami-hurricanes",
}

// Map Type of [cbsCode]TeamID
var CbsTeamCodeToTeamIDmapping map[string]string = map[string]string{
	"louisianamonroe-warhawks":              "ul-monroe-warhawks",
	"fiu-panthers":                          "florida-international-panthers",
	"connecticut-huskies":                   "uconn-huskies",
	"miami-fla-hurricanes":                  "miami-hurricanes",
	"middle-tenn-blue-raiders":              "middle-tennessee-blue-raiders",
	"saint-francis-u-red-flash":             "saint-francis-red-flash",
	"appalachian-state-mountaineers":        "app-state-mountaineers",
	"bethunecookman-wildcats":               "bethune-cookman-wildcats",
	"central-connecticut-state-blue-devils": "central-connecticut-blue-devils",
	"albany-great-danes":                    "ualbany-great-danes",
	"liu-sharks":                            "long-island-university-sharks",
	"se-missouri-st-redhawks":               "southeast-missouri-state-redhawks",
	"arkansaspine-bluff-golden-lions":       "arkansas-pine-bluff-golden-lions",
	"southeastern-louisiana-lions":          "se-louisiana-lions",
	"hawaii-rainbow-warriors":               "hawai'i-rainbow-warriors",
	"etsu-buccaneers":                       "east-tennessee-state-buccaneers",
	"grambling-state-tigers":                "grambling-tigers",
	"gardnerwebb-runnin-bulldogs":           "gardner-webb-runnin-bulldogs",
	"delaware-fightin-blue-hens":            "delaware-blue-hens",
	"army-west-point-black-knights":         "army-black-knights",
	"nc-at-aggies":                          "north-carolina-at-aggies",
	"mcneese-state-cowboys":                 "mcneese-cowboys",
	"southern-university-jaguars":           "southern-jaguars",
	"citadel-bulldogs":                      "the-citadel-bulldogs",
}

// Map Type of [foxCode]TeamID
var FoxTeamCodeToTeamIDmapping map[string]string = map[string]string{
	"saint-francis-red-flash":         "st-francis-pa-red-flash",
	"ut-martin-skyhawks":              "tennessee-martin-skyhawks",
	"app-state-mountaineers":          "appalachian-state-mountaineers",
	"central-connecticut-blue-devils": "central-connecticut-state-blue-devils",
	"ualbany-great-danes":             "university-at-albany-great-danes",
	"long-island-university":          "liu-sharks",
	"nicholls-colonels":               "nicholls-state-colonels",
	"se-louisiana-lions":              "southeastern-louisiana-lions",
	"grambling-tigers":                "grambling-state-tigers",
	"ul-monroe-warhawks":              "louisiana-monroe-warhawks",
	"nc-state-wolfpack":               "north-carolina-state-wolfpack",
	"southern-jaguars":                "southern-university-jaguars",
	"massachusetts-minutemen":         "umass-minutemen",
	"miami-hurricanes":                "miami-fl-hurricanes",
}
